version: '3.8'

services:
  phonebook_db:
    container_name: phonebook_db
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: 'phone_book_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      - '13306:3306'
    #expose:
     # - '13306'
    volumes:
      - local-db:/var/lib/mysql
    networks:
      - internal_network

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - internal_network
    depends_on:
      - phonebook_db

  phonebook_api:
    container_name: phonebook_api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - phonebook_db
    networks:
      - internal_network
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://phonebook_db:3306/phone_book_db

volumes:
  local-db:

networks:
  internal_network:
      driver: bridge